# Generated by Django 4.2.7 on 2023-12-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('predicted', models.IntegerField(choices=[(0, 'Student'), (1, 'Generated')])),
            ],
        ),
    ]
